from typing import Optional

class CypherCell:
    def __init__(self, data: bytes, volatile: bool = False, ttl_sec: Optional[int] = None) -> None: ...
    
    def __enter__(self) -> "CypherCell": ...
    
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    
    def reveal(self) -> str: ...
    
    def reveal_masked(self, suffix_len: int) -> str: ...
    
    def wipe(self) -> None: ...
    
    def __repr__(self) -> str: ...